# Generated by Django 6.0.4 on 2026-07-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindb',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quesans',
            name='mark',
            field=models.CharField(choices=[('R', 'R'), ('W', 'W')], default='W', max_length=1),
        ),
    ]
